# Generated by Django 4.1.4 on 2023-01-25 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='volunteer',
            field=models.ManyToManyField(related_name='patient_volunteer', to='volunteers.volunteer'),
        ),
        migrations.AddField(
            model_name='carer',
            name='patient',
            field=models.ManyToManyField(related_name='carer', to='patients.patient'),
        ),
    ]
