# Generated by Django 4.1 on 2023-01-26 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carer',
            old_name='email',
            new_name='careremail',
        ),
        migrations.RenameField(
            model_name='carer',
            old_name='name',
            new_name='carername',
        ),
    ]
