# Generated by Django 4.1 on 2023-01-27 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0001_initial'),
        ('patients', '0003_rename_email_carer_careremail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='volunteer',
        ),
        migrations.RemoveField(
            model_name='radiology',
            name='patient',
        ),
        migrations.AddField(
            model_name='patient',
            name='careremail',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='carername',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='carerphonenumber',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='volunteerp',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='volunteers.volunteer'),
        ),
        migrations.AddField(
            model_name='patient',
            name='x_ray',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='patients.radiology'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Carer',
        ),
    ]
