# Generated by Django 4.1 on 2023-01-27 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0001_initial'),
        ('patients', '0004_remove_patient_volunteer_remove_radiology_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='volunteerp',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='volunteers.volunteer'),
        ),
    ]
