# Generated by Django 4.1 on 2023-01-27 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_alter_patient_volunteerp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiology',
            name='x_ray',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
