# Generated by Django 4.1 on 2023-01-27 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_alter_radiology_x_ray'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='x_ray',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.radiology'),
        ),
    ]
