# Generated by Django 4.1.4 on 2023-01-25 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_birthdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='type',
        ),
        migrations.AddField(
            model_name='profile',
            name='usertype',
            field=models.CharField(choices=[('DR', 'Doctor'), ('CA', 'Carer'), ('PT', 'Patient')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
