# Generated by Django 4.1.4 on 2023-01-25 22:00

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('accounts', '0003_remove_profile_type_profile_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('doctorv', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='volunteer_doctors', to='doctors.doctor')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('accounts.profile', models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
